#!/bin/bash
# Quick test all shakiness features

echo "🎯 Testing FlowState Shakiness Detection System"
echo "================================================"
echo ""

# Test 1: Shakiness Analytics
echo "📊 Test 1: Checking shakiness analytics..."
cd "/Users/halaalzu/Downloads/Projects/Personal Projects/FlowState/FlowState"
python3 test_shakiness_analytics.py

echo ""
echo "================================================"
echo "✅ All 3 Features Implemented:"
echo ""
echo "1. 🆚 LEFT/RIGHT HAND COMPARISON"
echo "   • Visit: http://localhost:8080/hand-comparison"
echo "   • See side-by-side shakiness scores"
echo "   • Button added to analytics page"
echo ""
echo "2. 🎯 TRAINING MODE"
echo "   • Run: python training_mode.py"
echo "   • Collect labeled smooth/shaky data"
echo "   • Records 3 sessions per type"
echo ""
echo "3. 📤 DATA EXPORT"
echo "   • Run: python export_training_data.py"
echo "   • Creates: training_data_shakiness.csv"
echo "   • Ready for model retraining"
echo ""
echo "================================================"
echo "📝 Quick Start:"
echo ""
echo "  # Try training mode"
echo "  cd FlowState && python training_mode.py"
echo ""
echo "  # Compare your hands"
echo "  1. Record with LEFT hand on Freestyle"
echo "  2. Record with RIGHT hand on Freestyle"
echo "  3. Visit /hand-comparison"
echo ""
echo "  # Export data"
echo "  python export_training_data.py"
echo ""
echo "See SHAKINESS_TRAINING_GUIDE.md for full details!"
echo "================================================"
